# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:19
from __future__ import unicode_literals

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='', validators=[api.validators.validate_image_extension])),
                ('threshold', models.FloatField(default=0.5, help_text='threshold determines lightness')),
            ],
        ),
    ]
