# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='time_created',
        ),
        migrations.AddField(
            model_name='parameters',
            name='zoom',
            field=models.FloatField(default=0.5, help_text='zoom for page background estimation'),
        ),
    ]
