# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 00:55
from __future__ import unicode_literals

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170702_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterimage',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parameters',
            name='image',
            field=models.ImageField(null=True, upload_to='', validators=[api.validators.validate_image_extension]),
        ),
        migrations.DeleteModel(
            name='ParameterImage',
        ),
    ]
