# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170702_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='image',
        ),
    ]
