# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_parameters_nocheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='bignore',
            field=models.FloatField(default=0.1, help_text='ignore this much of the border for threshold estimation'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='escale',
            field=models.FloatField(default=1.0, help_text='scale for estimating a mask over the text region'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='hi',
            field=models.FloatField(default=90.0, help_text='percentile for white estimation'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='lo',
            field=models.FloatField(default=5.0, help_text='percentile for black estimation'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='maxskew',
            field=models.FloatField(default=2.0, help_text='skew angle estimation parameters'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='parallel',
            field=models.IntegerField(default=0, help_text='number of parallel processes to use'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='perc',
            field=models.FloatField(default=80.0, help_text='percentage for filters'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='range',
            field=models.IntegerField(default=20, help_text='range for filters'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='skewsteps',
            field=models.IntegerField(default=8, help_text='steps for skew angle estimation (per degree)'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='nocheck',
            field=models.BooleanField(default=True, help_text='disable error checking on inputs'),
        ),
    ]
